### ISSUE TITLE
Remove the need for scope range in `if` statements

### ISSUE THREAD

**Issue by bevinart** [BlidDev/Glang#4]
I feel that needing a scope range for the `if` statements makes coding in Glang tedious. I think an easy fix for this would be to add an end keyword, such as `end` or `fi`.

**Comment by BlidDev** [comment]
Adding an end keyword to if-statements was the original plan, however, because of statement nesting, adding an end keyword meant that every time a script is loaded and read, the program would have to go over the entire code and match the starts to the ends. This is completely fine in terms of performance of course, but such implementation is far beyond the scope of the project.
